scope:
  enabled: false

defaultBackend:
  enabled: false

controller:
  kind: "DaemonSet"
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: 34.7.138.153

  allowSnippetAnnotations: true
  extraEnvs:
    - name: TZ
      value: Europe/Amsterdam
  config:
    service-upstream: "true"
    enable-ocsp: "true"
    server-tokens: "false"
    http-redirect-code: "301"
  extraArgs:
    enable-ssl-passthrough: true
