scope:
  enabled: false

defaultBackend:
  enabled: false

controller:
  kind: "DaemonSet"
  service:
    externalTrafficPolicy: Local
    loadBalancerIP: 34.7.138.153

  allowSnippetAnnotations: true
  extraEnvs:
    - name: TZ
      value: Europe/Amsterdam
  config:
    service-upstream: "true"
    use-forwarded-headers: "true"
    compute-full-forwarded-for: "true"
    use-proxy-protocol: "false"
  extraArgs:
    enable-ssl-passthrough: true
